#include "bsdata.h"
#include "feat.h"

BSDATA(feati) = {
	{"NoExeptionalStrenght"},
	{"BonusSaveVsPoison"},
	{"BonusSaveVsSpells"},
	{"BonusVsElfWeapon"},
	{"BonusAttackVsHated"},
	{"BonusDamageVsEnemy"},
	{"BonusACVsLargeEnemy"},
	{"BonusHP"},
	{"UseMetal"},
	{"UseLeather"},
	{"UseShield"},
	{"UseMartial"},
	{"UseElvish"},
	{"UseRogish"},
	{"UsePriest"},
	{"UseMage"},
	{"TwoHanded"},
	{"Precise"},
	{"Deadly"},
	{"Natural"},
	{"Unique"},
	{"BloodSucking"},
	{"Disease"},
	{"Small"},
	{"Large"},
	{"Undead"},
	{"Paralized"},
	{"Moved"},
	{"Assembled"},
	{"ResistBludgeon"},
	{"ResistSlashing"},
	{"ResistPierce"},
	{"ResistFire"},
	{"ResistCold"},
	{"ResistCharm"},
	{"ResistSpells"},
	{"ImmuneNormalWeapon"},
	{"ImmuneFire"},
	{"ImmuneCold"},
	{"ImmuneCharm"},
	{"ImmuneSpells"},
	{"ImmuneDisease"},
	{"Enemy"},
	{"Ally"},
	{"Group"},
	{"You"},
	{"SeeMagical"},
	{"SeeCursed"},
	{"SeeIllusionary"},
};
assert_enum(feati, SeeIllusionary)